name: PCDS TwinCAT Standard Tests

on:
  workflow_call:
    inputs:
      project-root:
        required: false
        type: string
        default: "."
        description: "The root directory of the TwinCAT project"
      style-exclude:
        required: false
        type: string
        default: ""
        description: "Pattern (grep) of files to exclude from style checks"
      docs-organization:
        required: false
        type: string
        default: "pcdshub"
        description: "Organization for documentation deployment"

jobs:
  default:
    permissions:
      id-token: write  # Allow the job to generate an OIDC token
      contents: write
      pages: write
    runs-on: [self-hosted, Windows] 
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4
      - name: pre-commit
        uses: ./.github/workflows/pre-commit.yml
        with:
          project-root: ${{ inputs.project-root }}
          args: "--all-files"
  
      - name: summary
        uses: ./.github/workflows/twincat-summary.yml
        with:
          project-root: ${{ inputs.project-root }}
  
      - name: pragma-lint
        uses: ./.github/workflows/twincat-pragmalint.yml
        with:
          project-root: ${{ inputs.project-root }}
  
      - name: style-check
        uses: ./.github/workflows/twincat-style.yml
        with:
          project-root: ${{ inputs.project-root }}
          style-exclude: ${{ inputs.style-exclude }}
  
      - name: syntax-check
        uses: ./.github/workflows/twincat-syntax.yml
        with:
          project-root: ${{ inputs.project-root }}
  
      - name: documentation
        uses: ./.github/workflows/python-docs.yml
        with:
          deploy: ${{ github.repository_owner == inputs.docs-organization && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')) }}
          package-name: ""
          install-package: false
          docs-template-repo: "pcdshub/twincat-docs-template"
          docs-template-ref: "master"
